language: node_js
node_js:
- '0.10'
- '0.12'
before_script:
- npm install -g gulp jspm
- jspm config registries.github.auth $JSPM_GITHUB_AUTH_TOKEN
- jspm install
- npm install
script: gulp test
env:
  global:
    secure: OEa2Xb1dMtrxeqF5E2Ssef88B1w0EpR4ZzTAyz1Ne42YB2gluAmqno7dqzAYpT1AGz5WE51l9wLmRy6pA47R8H80kDGFVQ4YeNxUBy0Hr+cDAii9ID3t74j2YjA+LEtfvfAElid3tEEOpXwfoibTPlmLeE+SedfO2H+D/f6d9N09Kurhx3jKDKMqiQcVSjxAyKt0u1IZkL14UlmZrwmYC9hUuoYrH/dng8mKkFAbgx3N0cZJwnPTBGie4CFNvMNN+MFCb5P9xUc/XXvKXcSfOX+GSN+kP5nOwvIIUcQ7F95Slfyt9+B8PiOzBMRwPpRJZP60ftRWE3NGtMaEcR+GVpuXWBZByg3NPlU+B4TA81ccXtJDXLTK3BDIDEqGe5jPAeeRXoiX77CT9Tp+iPVU/2tS+RQJntiKyCw9hBRpC2hlN4w3WNHv+gsu4LpQsQzIauuk/yX6pwJHPcjd7zPgXCyDKpH2DBDIsFPK23vE8RndPdOt7aeZ/96yi22YCiWY4rQx+GeN1bbOol8iW+RfZOTzePy0OuqxYnkHRAn67gZOipwEDRykB5L/s513LL69QGJjFn0IxoVjXrHzNflgEI6lrjW17adRkoC9Yk1gjofnOHgRjcQgMK3ExjX2Ex4UCB+NQ0uBEpQXoFzjWdfmdaVy2DwGNLIo+c27wd2TtoI=
