language: node_js
node_js:
- '0.10'
- '0.12'
before_script:
- npm install -g gulp jspm
- jspm config registries.github.auth $JSPM_GITHUB_AUTH_TOKEN
- jspm install
script: gulp test
env:
  global:
    secure: X+UPJXkgOwGAt5yEXqLuqkf4YR9zAzXbFM+Nd/9MMXgsh14mKntb/O/1S+E3WG+PvmVWDgeFu8kNuHjSPtU1phG1Nq7wkhsDFTMNodLwxPIZI8wDBCZM2hlardWstPflG6oqOaicYRgeXmdlNnoIvx98Zmpoq2eqMnSp8SnWKErZLTorlm4PygSc0rz2xH4aRHT0Jf6gmdmF7UYv41JBLOP5oV+PD4QN+Dau41O5Xdm7smeOtUR48uXcR5PqlILbCkgzijmK5T+sm9kenrPi7ijnIaTtCljDIujcZMx2zhS53zsJ4jB8NZFGl2/pGDbUjTWeB52/GJvlEV7I8meqUMjK7pxLzC0a1qs05m0TeWSf008T+XSBXLBhsmLSOQtuwJSnqckmccOXnM3ok+JPL0ygcYy/zxQTGeCBldf+JBWuHStl4TwrofqV/pGVSAgBB+JjQ/0Uaap9O05RbXHC4dvNipxMjmUhUCqfSaAREZHAI1DNtKGPvg3SczhFZL2qTPqydGn4fc817m3yDsIHdUSdK/4QMWOy1HLgIgCjrLbSYZrZ2bxdG75GDMpNdpIyqdLrkcWPA8qd0u9kRnspwBi8nOz1htez5F/ZP41RhbgNK3ICbZ3BW2ppg9qtxwECTeIXmo417aeChCTkYEBKk1+KZUKPg0dsB+1VpHepDVI=
