language: node_js
node_js:
- '0.10'
- '0.12'
before_script:
- npm install -g gulp jspm
- jspm config registries.github.auth $JSPM_GITHUB_AUTH_TOKEN
- jspm install
script: gulp test
env:
  global:
    secure: WC0rcPymdIz5wok1mUxaTv+l5AItQHlcH4U1QVuwrcZTqJysfnMBmHYfJBTjk5uaGoM8LU+/LRFxa0I1wwekrk2VtddvM57Kuaf5fQrNJEaOkQQ0/qGyAwUjX0CVZ1tio7XOEnEVQnycnHcvOgyEGBDzbGJaS0yx9XNTvbdprSJOz+IKvxAS0u+BB49oeJ2F+KD562/j7yIIUvhLN+bP9jT+n0K7e/Mj6QwD4vWWS/VoIymiJW/xtN/lQhwT3J0kBHGiVHuyC0CGrtCjOJuOJotWwmxxaoH9qobjaLjfSuo0ivnDObVZEbl12ZIgRS5RGvKtm2RFhP60XqIOjlg82YEJ+7UAxYiV9MTwcgzEMb1oSeaVNWQ3Z/tn/RG95fP33kstjCunjAI2lilfe19gVniSX1uMSbO3IhRXp5wMqG7luly7Ekazm1QYfkJYUB9v+VUpN995W/Fs/t1FqxzO1s68Lbg4q1cPUrzdKv+kFi6Bf0/e3wgYog6tbvT2cA6dRjBC8PSsOTG9nZ3x0RpT0m/kVBclRuh3OAHLGtb4hPUMHHWkWi16oWImU+iyr7CGI52fBEoIbuzXA8iS5k6QbwNkRJZTui+pH5Z/EI5rVZ4shRy/iQDa6MZ9KD7ZzzFSn/lGqMQC6DdJJXtzBSSnbPg38jgF0JgnkMXOKS5WSmQ=
